### ISSUE TITLE
isPurchasing with Consumables

### ISSUE THREAD

**Issue by oxcug** [Bonobolabs/ios-in-app-purchasing#2]
When I purchase a consumable, the isPurchasing state gets fired the first time I purchase it, however when I purchase it a second or more times, it doesn't read it and instead gives me the following error message:

 WARNING! Tried to appy event SetPurchasing while in state Purchased.

**Comment by pzmudzinski** [comment]
Have you fixed this issue? Is anyone working on this lib? :zzz:

**Comment by dZbear** [comment]
I have fixed my issue of RE-purchasing a consumable, let me know if you'd like to know the fix.

**Comment by pzmudzinski** [comment]
Yes, please. Are you recommending this library anyway?

**Comment by x0661t** [comment]
Would be great if you post fixed lib here

**Comment by dZbear** [comment]
Here's the link to my modified lib to support re-purchasing :
https://dl.dropbox.com/u/96564087/InAppPurchasing/InAppPurchasing.zip

Basically, I added a state in the Finite State Machine for when the item is
in the Purchased state, enabling it to go from Purchased
to Purchasing again.
This does mean that if you have in-app purchases that can only be bought
once, you need to make the check in the app layer to make sure the user
doesn't buy it twice.

Let me know if that worked for you. Feel free to add me on skype
(md_lasalle).

**Comment by pzmudzinski** [comment]
Thanks man, that's great. Could you tell me how are you saving information about products bought by user? 
What if user delete app and install it again? Let's say user buys consumable inapp purchase (providing 10 potions for example) and you save this info in standardUserDefaults. Then he eats 5 of them, but after that he reinstall app. There's no saved data but you know that he bought 10 potions before from Apple's server. How can I retrieve information about already used 5 of them? Do I need any external server?

**Comment by x0661t** [comment]
use iCloud for this. Keep your data at *.plist file at iCloud. User purchase coins, you provide him with coins and write it to your plist, than sync it with cloud.

**Comment by oxcug** [comment]
Is it bad that I'm only just noticing this 😆
